project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - iterations.qmd
    - try.qmd
    - files-configurations.qmd
    - files-header-table.qmd
    - files-many.qmd
    - tables-math.qmd
    - lists-indexing.qmd
website:
  title: "Coding at the Tandy Center for Ocean Forecasting"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: iterations.qmd
        text: "Iterations"
      - href: try.qmd
        text: "You're very trying"
      - href: files-configurations.qmd
        text: "Configuration files"
      - href: files-header-table.qmd
        text: "Files with bad headers"
      - href: files-many.qmd
        text: "E pluribus unum"
      - href: tables-math.qmd
        text: "Table math"
      - href: lists-indexing.qmd
        text: "Lists"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

